m09w24/the-it-crowd/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'login', action: :index, controller: 'users'
  # get 'login', to: 'users#index'

  # resources :characters
  # resources :quotes

  resources :characters do
    resources :quotes
  end
end

m09w24/the-it-crowd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

m09w24/the-it-crowd/app/models/character.rb
class Character < ApplicationRecord
  has_many :quotes # character.quotes
end

m09w24/the-it-crowd/app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :character # quote.character
end

m09w24/the-it-crowd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

m09w24/the-it-crowd/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end
end

m09w24/the-it-crowd/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    character_id = params[:character_id]
    @character = Character.find character_id

    @quotes = @character.quotes

    render json: {
      character: @character,
      quotes: @quotes
    }
  end
end

m09w24/the-it-crowd/app/helpers/application_helper.rb
module ApplicationHelper
end

m09w24/the-it-crowd/app/helpers/character_helper.rb
module CharacterHelper
end

m09w24/the-it-crowd/app/helpers/characters_helper.rb
module CharactersHelper
end

m09w24/the-it-crowd/app/helpers/quotes_helper.rb
module QuotesHelper
end

m09w24/the-it-crowd/app/views/characters/index.html.erb
<h1>All the characters!</h1>


<% @characters.each do |character| %>
  <div class="character">
    <h2>Actor: <%= character.actor %></h2>
    <h2>Name: <%= character.name %></h2>
    <%= link_to "Quotes", character_quotes_path(character.id) %>
  </div>
<% end %>

m09w24/the-it-crowd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheItCrowd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

m09w24/the-it-crowd/app/views/quotes/index.html.erb
<h1>All the quotes from <%= @character.name %></h1>

<%= link_to "All the characters", characters_path %>

<% @quotes.each do |quote| %>
  <div class="quote">
    <h2>Email: <%= quote.email %></h2>
    <h2>Quote: <%= quote.quote %></h2>
    <h2>Character: <%= quote.character.name %></h2>
  </div>
<% end %>